thread '<unnamed>' panicked at py-polars/src/map/series.rs:213:19:
python function failed GEOSException: ParseException: Expected word but encountered end of stream
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
